using App.Core.Enums;

namespace App.Core.Models
{
    public class Account
    {
        /// <summary>
        /// Id is generated by the service during Add(), not by the form.
        /// Default empty string to allow new() without initializer.
        /// </summary>
        public string Id { get; set; } = string.Empty;

        /// <summary>
        /// Required: form must provide a name.
        /// </summary>
        public required string Name { get; set; }

        public string? Email { get; set; }
        public AccountTypeEnum AccountType { get; set; }
        public decimal OpeningBalance { get; set; }
        public string Currency { get; set; } = "PKR";
        public AccountStatusEnum AccountStatus { get; set; } = AccountStatusEnum.Active;
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}
