using App.Core.Enums;

namespace App.Core.Models
{
    public class Category
    {
        /// <summary>
        /// Id is generated by the service during Add(), not by the form.
        /// Default empty string to allow new() without initializer.
        /// </summary>
        public string Id { get; set; } = string.Empty;

        /// <summary>
        /// Required: form must provide a name.
        /// </summary>
        public required string Name { get; set; }

        public CategoryTypeEnum CategoryType { get; set; }
        public decimal? MonthlyBudget { get; set; }
        public CategoryStatusEnum CategoryStatus { get; set; } = CategoryStatusEnum.Active;
    }
}
