using App.Core.Enums;

namespace App.Core.Models
{
    public class Transaction
    {
        /// <summary>
        /// Id is generated by the service during Add(), not by the form.
        /// Default empty string to allow new() without initializer.
        /// </summary>
        public string Id { get; set; } = string.Empty;

        /// <summary>
        /// Required: form must provide account reference.
        /// </summary>
        public required string AccountId { get; set; }

        /// <summary>
        /// Required: form must provide category reference.
        /// </summary>
        public required string CategoryId { get; set; }

        public decimal Amount { get; set; }
        public DateTime TransactionDate { get; set; } = DateTime.UtcNow;
        public string? Description { get; set; }
        public bool IsRecurring { get; set; } = false;
        public RecurringFrequencyEnum? RecurringFrequency { get; set; }
        public TransactionStatusEnum TransactionStatus { get; set; } = TransactionStatusEnum.Cleared;
    }
}
